using System.Text.RegularExpressions;
using TechSolutions_IPS_HW.Security.Interfaces;

namespace TechSolutions_IPS_HW.Security.Services;

public partial class HtmlSanitizerService : IHtmlSanitizerService
{

    //Snures that html provided is sanitized to prevent Cross-site scripting (XSS) attacks. It removes potentially dangerous tags and attributes.
    public string Sanitize(string? html)
    {
        if (string.IsNullOrWhiteSpace(html)) return string.Empty;

        var sanitized = html.Trim();

        sanitized = UnsafeBlockTagRegex().Replace(sanitized, string.Empty);
        sanitized = UnsafeSingleTagRegex().Replace(sanitized, string.Empty);
        sanitized = EventAttributeRegex().Replace(sanitized, string.Empty);
        sanitized = JsProtocolRegex().Replace(sanitized, "$1=\"#\"");

        return sanitized.Trim();
    }

    //These below was generated by AI, figuring out regex everytime for a specific task is a little waste of time
    [GeneratedRegex("<(script|iframe|object|embed|form|input|button|textarea|select|option|meta|link|base|frame|frameset|applet)[^>]*?>.*?</\\1>", RegexOptions.IgnoreCase | RegexOptions.Singleline)]
    private static partial Regex UnsafeBlockTagRegex();

    [GeneratedRegex("<(script|iframe|object|embed|form|input|button|textarea|select|option|meta|link|base|frame|frameset|applet)[^>]*?/?>", RegexOptions.IgnoreCase)]
    private static partial Regex UnsafeSingleTagRegex();

    [GeneratedRegex("\\son[a-z]+\\s*=\\s*(\"[^\"]*\"|'[^']*'|[^\\s>]+)", RegexOptions.IgnoreCase)]
    private static partial Regex EventAttributeRegex();

    [GeneratedRegex("\\b(href|src)\\s*=\\s*(\"\\s*javascript:[^\"]*\"|'\\s*javascript:[^']*'|\\s*javascript:[^\\s>]+)", RegexOptions.IgnoreCase)]
    private static partial Regex JsProtocolRegex();
}
